### ISSUE TITLE
Renaming a group empties it

### ISSUE THREAD

**Issue by schirinowski** [TheLastProject/Catima#142] opened 2021-01-28 04:58 UTC
I just migrated from Loyalty Card Keychain. Groups is a great new feature. When playing around with it, I renamed a group. It immediately removed all cards from this group, leaving it empty.
I would have expected the group to exist further as it was, except for having the new name.

**Comment by TheLastProject** [comment] 2021-01-28 08:03
I just tried and can reproduce this issue. Can't believe I missed this. I will fix this soon

**Comment by schirinowski** [comment] 2021-01-28 08:39
Nah, no worries! And don't be so cruel to yourself. 😉
Thanks for getting on it! 👍

**Comment by TheLastProject** [comment] 2021-01-28 09:39
For context: the bug seems to be that the table that links the groups to the cards is not correctly updated. Renaming it back to the old name restores the link. I would recommend doing that before updating to the next release where I'll fix this so you can rename it as you want without issues.

**Comment by TheLastProject** [comment] 2021-01-28 18:33
Fixed in https://github.com/TheLastProject/Catima/commit/99a38499423ac48f8d7f49485d74ec2cfdeb0af5. Thank you so much for the report. I'll make a new release with this bugfix in it.

**Closed by TheLastProject** 2021-01-28 18:33 UTC
Labels: bug

**Comment by schirinowski** [comment] 2021-01-28 19:20
Excellent, I'll test as soon as F-Droid rolls it out to me. Thanks!

**Comment by schirinowski** [comment] 2021-02-01 22:19
Works like a charm, thanks for fixing, Sylvia! 😊

**Comment by TheLastProject** [comment] 2021-02-01 22:22
Thanks for confirming it's working for you now, that's super appreciated :)
