### ISSUE TITLE
Theme regressions

### ISSUE THREAD

**Issue by evelikov** [TheLastProject/Catima#110] opened 2020-11-26 14:10 UTC
Thanks for picking Loyalty Card Keychain and continuing the project.

Switching from it I've noticed a few small regressions:
 - the "Dark" theme is now "Black" 
Android is a bit inconsistent on the topic, thus some apps have "light" "dark" and "black"
 - the header in the Settings screen is the wrong color
Black instead of red.
 - the checkboxes in the Settings screen are misaligned
Might be worth even using Switch(es), for Android design reasons and people with fat fingers (the Switch hitbox is larger)

Thanks in advance

**Comment by TheLastProject** [comment] 2020-11-26 14:26
>the "Dark" theme is now "Black"

Putting both apps side by side I can see the difference, yeah, but I am not sure if I would call it a regression. It seems to be mostly personal taste too.

>the header in the Settings screen is the wrong color
>Black instead of red.

Hmm yeah that is something that broke in the dark theme

>the checkboxes in the Settings screen are misaligned

I... really can't tell

> Might be worth even using Switch(es), for Android design reasons and people with fat fingers (the Switch hitbox is larger)

The whole row actually toggles that setting, not just the checkboxes, so I don't think this is an issue.

**Comment by evelikov** [comment] 2020-11-26 14:48
> > the checkboxes in the Settings screen are misaligned
> 
> I... really can't tell
> 
Toggle the "Show layout bounds" in the Developer options on the device/emulator. IIRC there is also a way to see in the Android Studio.

This and the checkbox/switch aren't that much of an issue - merely mentioning for completeness sake.

**Comment by TheLastProject** [comment] 2020-11-26 17:06
Ah, thanks. I don't think I'll spend time trying to fix it though. The alignment issue is unnoticeable for me and these are very very very minor issues that will take many many hours to get fixed. It's just not worth the time imho (although patches welcome if you feel it is worth your time).

The header in settings is the only thing i really consider a bug here yet I have no clue why it even started doing this. Android and UI is... pretty messy.

**Comment by ltGuillaume** [comment] 2020-12-10 22:01
Also, the arrow up/down (to show/hide the note) is stretched and blurry (even on a 720p screen).

**Comment by TheLastProject** [comment] 2020-12-10 22:03
Hmm, I guess I've been staring at that one for so long I didn't notice it was blurry. I should figure out how to properly make Android always use SVG, it sometimes complains with weird errors but SVGs are just so much better than PNGs.

**Comment by ltGuillaume** [comment] 2020-12-10 22:05
Agreed!

**Comment by TheLastProject** [comment] 2020-12-10 22:52
The blurriness of icons should be fixed in 9bf245a392ac89309e6b32d9685887678176bc79. Gonna keep running this for some days to make sure nothing breaks with using SVG everywhere.

**Comment by ltGuillaume** [comment] 2020-12-10 22:54
Great! Thank you so much!

**Comment by TheLastProject** [comment] 2021-08-21 23:16
The main issue left here, the header, was fixed in #340, thanks to @subhashishanand. I'll close this issue now :)

**Closed by TheLastProject** 2021-08-21 23:16 UTC
Labels: bug, help wanted
