### ISSUE TITLE
[Android 5] Bug when changing max font size: scaling of the size of the cards

### ISSUE THREAD

**Issue by Altonss** [TheLastProject/Catima#635] opened 2021-11-29 20:01 UTC
This has been achieved by setting a lower maximum size for the card: I maybe did something like 200% then 50%
![image](https://user-images.githubusercontent.com/66519591/143934546-b425340e-057e-4188-8ef1-58c263f05b64.png)

**Comment by TheLastProject** [comment] 2021-11-29 20:08
Hmm, weird, I can't reproduce this one myself.

**Comment by Altonss** [comment] 2021-11-29 20:17
> Hmm, weird, I can't reproduce this one myself.

# How I could produce this:
## System information:
- Android 5.0.1
- Device: Samsung Galaxy Core Prime

## Steps:
- Set the max font size to 100% (which should be the default setting)
- Have one card with several words so that the card title takes up several lines
- Change the max font size to 50%
- View the result!
-

**Comment by TheLastProject** [comment] 2021-11-29 20:33
Ah, I can reproduce it in an Android 5 emulator, it works fine on Android 10. Not sure what would cause this, I am lowering the priority because it only happens on old Android after changing a setting and you can restart the app to fix it, but I do still consider this a bug that should be fixed.

**Comment by Altonss** [comment] 2021-11-29 20:35
> Not sure what would cause this, I am lowering the priority because it only happens on old Android after changing a setting and you can restart the app to fix it,

Yes I understand that's normal! It's really not an important/bad issue as it was just me trying to find the limits/the bugs. ^^
It's still a bug, but the priority is very low :)

**Comment by TheLastProject** [comment] 2021-11-29 20:39
I appreciate you reporting these bugs, even if they're minor bugs! It's still very good as a developer to be aware of what issue there could be, so thank you for reporting! :+1:

**Comment by TheLastProject** [comment] 2021-12-16 09:41
Should be fixed in #675

**Closed by TheLastProject** 2021-12-16 09:41 UTC
Labels: bug, help wanted
