### ISSUE TITLE
Save cards into choosen folder as a file + encrypted files

### ISSUE THREAD

**Issue by trymeouteh** [TheLastProject/Catima#317] opened 2021-08-06 03:08 UTC
Please add a setting to save your cards in an choose directory as a file. This way you can use another app alongside such as Syncthing and Nextcloud to have your cards backup automatically. Essentually you can choose a folder on your phone and each card will be saved into this folder as a file.

And to have a setting to enter in a password to have these files encrypted. This will be an additional security feature which the app can encrypt and decrypt the card file with the password that is entered in the app

**Comment by TheLastProject** [comment] 2021-08-06 07:22
This seems to be a duplicate of #23 and #40 (for users on devices without Seedvault).

**Closed by TheLastProject** 2021-08-06 07:22 UTC
