### ISSUE TITLE
Add an option to attach a photo of a card [feature suggestion]

### ISSUE THREAD

**Issue by selivan** [TheLastProject/Catima#210] opened 2021-04-25 18:55 UTC
Some cards do not have a barcode of a number, just "discount to the bearer of this". And even for cards with a number/barcode it might be a convenient feature to decrease salesperson confusion(not everybody used to cards on the phone). I suppose on CVS export this photo may be saved in base64.

Anyway, thanks for the useful app, may be I will finally start to use discounts, now that it does not require to haul a ton of plastic with me.

**Comment by TheLastProject** [comment] 2021-04-25 19:46
Duplicate of #15.

**Closed by TheLastProject** 2021-04-25 19:46 UTC
